# Generated by Django 3.2.9 on 2021-12-01 15:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dahboard',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=45, null=True)),
                ('banner_subtitle', wagtail.core.fields.RichTextField(null=True)),
                ('child_detail', wagtail.core.fields.StreamField([('child_data', wagtail.core.blocks.StructBlock([('child_details', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('identity_no', wagtail.core.blocks.CharBlock(help_text='This an autogenerated number', required=True)), ('district', wagtail.core.blocks.CharBlock(help_text='District', required=True)), ('health_center', wagtail.core.blocks.CharBlock(help_text='Where Child got Registered', required=True)), ('child_name', wagtail.core.blocks.CharBlock(help_text='Childe Name', required=True)), ('sex', wagtail.core.blocks.CharBlock(help_text='Sex', required=True)), ('dob', wagtail.core.blocks.CharBlock(help_text='Date of Birth', required=True)), ('birth_weight', wagtail.core.blocks.CharBlock(help_text='Weight of child in Kilograms', required=True)), ('birth_order', wagtail.core.blocks.CharBlock(help_text='Child Birth Order', required=True)), ('subcounty', wagtail.core.blocks.CharBlock(help_text='Sub-County', required=True)), ('parish', wagtail.core.blocks.CharBlock(help_text='Parish', required=True)), ('lc1', wagtail.core.blocks.CharBlock(help_text='Village', required=True)), ('special_care', wagtail.core.blocks.CharBlock(help_text='Tick reason for Special Care', required=True)), ('other_reasons', wagtail.core.blocks.CharBlock(help_text='Any other reason for special attention', required=True))]))), ('mother_details', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('mother_name', wagtail.core.blocks.CharBlock(help_text="Mother's Name", required=True)), ('mother_occupation', wagtail.core.blocks.CharBlock(help_text="Mother's Occupation", required=True)), ('nin', wagtail.core.blocks.CharBlock(help_text='National Identification Number', required=True)), ('father_name', wagtail.core.blocks.CharBlock(help_text="Father's Name", required=True)), ('father_occupation', wagtail.core.blocks.CharBlock(help_text="Father's Occupation", required=True))])))]))])),
                ('banner_cta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('banner_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
