# Generated by Django 3.2.9 on 2021-12-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunisation', '0002_auto_20211202_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immunization',
            old_name='vaccine_status',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='vitaminanddeworming',
            old_name='vitamin_a_status',
            new_name='title',
        ),
        migrations.AddField(
            model_name='educationandcounselling',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='growthpromotionchart',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='immunization',
            name='vaccine_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infantgrowth',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pmtct',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vitaminanddeworming',
            name='vitamin_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
