# Generated by Django 3.2.9 on 2021-12-02 15:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('immunisation', '0004_auto_20211202_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDetails',
            fields=[
                ('title', models.CharField(max_length=100, null=True)),
                ('child_id', models.AutoField(primary_key=True, serialize=False, unique_for_year=True)),
                ('child_district', models.CharField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1, max_length=50, null=True)),
                ('health_facility', models.CharField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1, max_length=50, null=True)),
                ('child_name', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('birth_order', models.IntegerField(null=True)),
                ('birth_weight', models.IntegerField(null=True)),
                ('special_care', models.CharField(blank=True, choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1, max_length=50, null=True)),
                ('other_special_care', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationAndCounselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('education_date', models.DateField(null=True)),
                ('next_date', models.DateField(null=True)),
                ('education_Info', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthPromotionChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('time_period', models.CharField(max_length=100, null=True)),
                ('where_to_give', models.CharField(max_length=100, null=True)),
                ('how_to_give', models.CharField(max_length=100, null=True)),
                ('vaccine_date', models.DateField(null=True)),
                ('vaccine_name', models.CharField(max_length=100, null=True)),
                ('vaccine_comments', models.TextField(max_length=100, null=True)),
                ('child_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immunisation.childdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InfantGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('child_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immunisation.childdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('mother_id', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('mother_occupation', models.CharField(max_length=50, null=True)),
                ('mother_education', models.CharField(max_length=50, null=True)),
                ('father_id', models.CharField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('father_occupation', models.CharField(max_length=50, null=True)),
                ('father_education', models.CharField(max_length=50, null=True)),
                ('father_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('child_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immunisation.childdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Pmtct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('pmtct_code', models.CharField(max_length=100, null=True)),
                ('did_child_initate_treatment', models.BooleanField()),
                ('date_initated', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VitaminAndDeworming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('vitamin_a_date', models.DateField(null=True)),
                ('vitamin_name', models.CharField(max_length=100, null=True)),
                ('vitamin_a_comments', models.TextField(max_length=100, null=True)),
                ('deworming_date', models.DateField(null=True)),
                ('deworming_status', models.CharField(max_length=100, null=True)),
                ('deworming_comments', models.TextField(max_length=100, null=True)),
                ('given_at_age', models.CharField(max_length=100, null=True)),
                ('child_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immunisation.childdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Dahboard',
        ),
        migrations.AddField(
            model_name='educationandcounselling',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immunisation.parentdetails'),
        ),
    ]
